
version: '3'
services:
  front:
    container_name: frontend
    build: ./dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      NUXT_ENV_API_DNS: ${NUXT_ENV_API_DNS}
    working_dir: /app
    command: >
      ash -c 'npm install &&
      npm run dev'
    networks:
    - test-network

networks:
  test-network:
    external: true
