version: '3'

services:
  client:
    build: .
    container_name: client-container
    networks:
      - client_network
    volumes:
      - .:/app
      - /app/node_modules
    command: "npm run dev"
networks:
  client_network:
    external: true
