version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.0.0
  aws-ecs: circleci/aws-ecs@1.1.0
jobs:
  test:
    docker:
      - image: circleci/node:10.16.3
    # working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
workflows:
  version: 2
  workflow:
    jobs:
      - test
      # dockerイメージのビルド & ECRへプッシュ
      - aws-ecr/build-and-push-image:
          # テストをパスしたら実行
          requires:
            - test
          filters:
            branches:
              only: master
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          tag: ${CIRCLE_SHA1}
      - aws-ecs/deploy-service-update:
          # イメージのビルド & プッシュが成功したら実行
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only: master
          aws-region: ${AWS_REGION}
          family: ${ECS_SERVICE}
          cluster-name: '${ECS_CLUSTER}'
          container-image-name-updates: 'container=${ECS_SERVICE},image-and-tag=${AWS_ECR_ACCOUNT_URL}/${ECR_REPOSITORY_NAME}:${CIRCLE_SHA1}'

      # dockerイメージのビルド & ECRへプッシュ
      # - aws-ecr/build-and-push-image:
      #     # テストをパスしたら実行
      #     requires:
      #       - test
      #     dockerfile: Dockerfile
      #     path: .
      #     filters:
      #       branches:
      #         only: master
      #     region: AWS_REGION
      #     account-url: AWS_ECR_ACCOUNT_URL
      #     repo: ${ECR_REPOSITORY_NAME}
      #     tag: ${CIRCLE_SHA1}
