version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: スクリプトチェック
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Dockerネットワーク作成
          command: docker network create test-network
      - run: 
          name: 起動
          command: docker-compose up -d
      - run:
          name: protocol buffersによるコード生成
          command: make generate
      - run:
          name: lint
          command: make lint

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build:
          requires:
            - shellcheck
