version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: スクリプトチェック
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Dockerネットワーク作成
          command: docker network create client_network
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run: 
          name: ビルド
          command: docker-compose build
      - save_cache: # 依存関係キャッシュを保存する特別なステップ
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: 
          name: 起動
          command: docker-compose up -d
      - run:
          name: protocol buffersによるコード生成
          command: make generate
      - run:
          name: lint
          command: make lint

workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build:
          requires:
            - shellcheck
