version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-ecr: circleci/aws-ecr@6.0.0
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: スクリプトチェック
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources
  test:
    docker:
      - image: circleci/node:10.16.3
    # working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: lint
          command: npm run lint
workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - test:
          requires:
            - shellcheck
      # dockerイメージのビルド & ECRへプッシュ
      - aws-ecr/build-and-push-image:
          # テストをパスしたら実行
          requires:
            - test
          dockerfile: Dockerfile
          path: .
          filters:
            branches:
              only: master
          region: AWS_REGION
          account-url: AWS_ECR_ACCOUNT_URL
          repo: ${ECR_REPOSITORY_NAME}
          tag: ${CIRCLE_SHA1}
